/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118772-ge4c8e80a2e-20250314"
#endif /* AVUTIL_FFVERSION_H */
